global:
  scrape_interval:     5s # Default scrape interval

scrape_configs:


  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    scheme: https
    static_configs:
      - targets: ['homelab:8442']
        labels:
          application: 'My Spring Boot Application'
    tls_config:
        # Prometheus will check that the node_exporter presents a certificate
        # signed by this ca.
        ca_file: '/rootca/rootCA.crt'
        # The cert and key are presented to node_exporter to authenticate
        # Prometheus as a client.
        cert_file: '/clientca/externalclient.crt'
        key_file: '/clientca/externalclient.key'
        #insecure_skip_verify: true
        
    

  